logger:
  default: debug
  logs:
    homeassistant.components.telegram_bot: critical

homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 15
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include customize.yaml

frontend:

lovelace:
  mode: yaml

config:

http:

updater:

conversation:

recorder:
  purge_keep_days: 3
  include:
    domains:
      - input_datetime
      - input_number
      - light
      - script
      - binary_sensor
    entities:
      - sensor.current_version
      - sensor.processor_use
      - sensor.memory_use_percent
      - sensor.disk_use_percent
      - sensor.processor_temp

history:

logbook:

hassio:

sun:

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password

telegram_bot:
  - platform: polling
    api_key: !secret bot_key
    allowed_chat_ids:
      - !secret alex_chat_id

ifttt:
  key: !secret ifttt_key

yeelight:
  devices:
    10.192.168.65:
      name: Luce RGB
      transition: 500

light:
  - platform: mqtt
    name: Luce bianca
    state_topic: stat/luce-bianca/POWER
    command_topic: cmnd/luce-bianca/POWER
    qos: 0
#   - platform: mqtt
#     name: Luci natale sala
#     state_topic: stat/natale-sala/POWER
#     command_topic: cmnd/natale-sala/POWER
#     qos: 1
#   - platform: mqtt
#     name: Luci natale studio
#     state_topic: stat/natale-studio/POWER
#     command_topic: cmnd/natale-studio/POWER
#     qos: 1
#   - platform: template
#     lights:
#       luci_albero:
#         friendly_name: Luci albero
#         turn_on:
#           service: ifttt.trigger
#           data:
#             event: accendi_albero
#         turn_off:
#           service: ifttt.trigger
#           data:
#             event: spegni_albero

binary_sensor:
  - platform: mqtt
    name: Porta
    state_topic: stat/interruttore-camera/POWER2
    device_class: door
    qos: 0
  - platform: mqtt
    name: Interruttore
    state_topic: stat/interruttore-camera/POWER1
    qos: 0

sensor:
  - platform: uptime
    unit_of_measurement: hours
  - platform: version
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: memory_use_percent
      - type: disk_use_percent
        arg: /
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: command_line
    name: Processor temp
    command: 'cat /sys/class/thermal/thermal_zone0/temp'
    unit_of_measurement: '°C'
    value_template: '{{ value | multiply(0.001) | int }}'
  - platform: command_line
    name: Auto update log
    command: 'head -c 254 /config/auto-update.log'
    scan_interval: 3600

notify:
  - name: Alex
    platform: telegram
    chat_id: !secret alex_chat_id

input_number:
  minuti_luci_off:
    name: Minuti luci OFF
    min: 2
    max: 10
    step: 1

input_datetime:
  sveglia:
    name: Sveglia
    has_date: false
    has_time: true

rest_command:
  update_ip:
    url: !secret update_ip_url
    method: GET

shell_command:
  auto_update: 'cd /config && cp auto-update.log auto-update_old.log && sh auto-update.sh &> auto-update.log'

group: !include groups.yaml
automation: !include automations_hw.yaml
script: !include scripts_hw.yaml
