system_health:

logger:
  default: info

homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 15
  unit_system: metric
  time_zone: Europe/Rome
  whitelist_external_dirs:
    - /tmp

frontend:

lovelace:
  mode: yaml

config:

http:

updater:

conversation:

recorder:
  purge_keep_days: 3
  include:
    domains:
      - input_datetime
      - input_number
      - input_boolean
      - light
      - switch
      - script
      - binary_sensor
    entities:
      - sensor.current_version
      - sensor.processor_use
      - sensor.memory_use_percent
      - sensor.disk_use_percent
      - sensor.processor_temp
      - sensor.ip_camera_battery_level
      - sensor.ip_camera_battery_temperature
      - sensor.ip_camera_battery_voltage
      - sensor.ip_camera_light_level

history:

logbook:

hassio:

sun:

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password

telegram_bot:
  - platform: polling
    api_key: !secret bot_key
    allowed_chat_ids:
      - !secret alex_chat_id

ifttt:
  key: !secret ifttt_key

yeelight:
  devices:
    10.192.168.71:
      name: Luce RGB
      transition: 500

android_ip_webcam:
  - host: 10.192.168.65
    port: 8080
    name: IP Camera
    username: !secret ipc_user
    password: !secret ipc_pass
    sensors:
      - battery_level
      - battery_temp
      - battery_voltage
      - light

light:
  - platform: mqtt
    name: Luce bianca
    state_topic: stat/luce-bianca/POWER
    command_topic: cmnd/luce-bianca/POWER
    qos: 0
# Luci natale
  - platform: mqtt
    name: Luci natale sala
    state_topic: stat/luci-natale-sala/POWER
    command_topic: cmnd/luci-natale-sala/POWER
    qos: 1
  - platform: mqtt
    name: Luci natale terrazzo
    state_topic: stat/luci-natale-terrazzo/POWER
    command_topic: cmnd/luci-natale-terrazzo/POWER
    qos: 1
  - platform: mqtt
    name: Albero di natale
    state_topic: stat/albero-di-natale/POWER
    command_topic: cmnd/albero-di-natale/POWER
    qos: 1
  - platform: template
    lights:
      stella_di_natale:
        friendly_name: Stella di natale
        turn_on:
          service: ifttt.trigger
          data:
            event: accendi_stella_di_natale
        turn_off:
          service: ifttt.trigger
          data:
            event: spegni_stella_di_natale

switch:
  - platform: mqtt
    name: Carica telefono
    state_topic: stat/tel-carica/POWER
    command_topic: cmnd/tel-carica/POWER
    qos: 1

binary_sensor:
  - platform: mqtt
    name: Porta
    state_topic: stat/interruttore-camera/POWER2
    device_class: door
    qos: 0
  - platform: mqtt
    name: Interruttore
    state_topic: stat/interruttore-camera/POWER1
    qos: 0
  - platform: ping
    name: Stato rete
    host: 1.1.1.1
    count: 3
    scan_interval: 30

sensor:
  - platform: uptime
    unit_of_measurement: hours
  - platform: version
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: memory_use_percent
      - type: disk_use_percent
        arg: /
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: command_line
    name: Processor temp
    command: 'cat /sys/class/thermal/thermal_zone0/temp'
    unit_of_measurement: '°C'
    value_template: '{{ value | multiply(0.001) | int }}'
  - platform: command_line
    name: Auto update log
    command: 'head -c 254 /config/auto-update.log'
    scan_interval: 3600

notify:
  - name: Alex
    platform: telegram
    chat_id: !secret alex_chat_id

input_number:
  minuti_luci_off:
    name: Minuti luci OFF
    min: 2
    max: 5
  delay_sorveglia:
    name: Delay sorveglia
    min: 1
    max: 180
    mode: box

input_datetime:
  ora_sveglia:
    name: Ora sveglia
    has_date: false
    has_time: true
# Luci natale
  luci_natale_ora_on:
    name: Ora accensione
    has_date: false
    has_time: true
  luci_natale_ora_off:
    name: Ora spegnimento
    has_date: false
    has_time: true
  luci_albero_ora_off:
    name: Ora spegnimento albero
    has_date: false
    has_time: true

input_boolean:
  sveglia:
    name: Sveglia

rest_command:
  update_ip:
    url: !secret update_ip_url
    method: GET

shell_command:
  auto_update: 'cd /config && sh auto-update.sh &> auto-update.log'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
