title: Home assistant

views:
  - title: Main
    id: main
    cards:
      - type: entities
        title: Raspberry
        show_header_toggle: false
        entities:
          - sensor.processor_use
          - sensor.processor_temp
          - sensor.memory_use_percent
          - sensor.disk_use_percent
          - sensor.uptime
      - type: entities
        title: IPC Info
        show_header_toggle: false
        entities:
          - entity: switch.carica_telefono
            state_color: true
          - sensor.ip_camera_battery_level
          - sensor.ip_camera_battery_temperature
          - sensor.ip_camera_battery_voltage
          - sensor.ip_camera_light_level
      - type: picture-entity
        entity: camera.ip_camera
      - type: glance
        title: Camera
        columns: 4
        show_state: false
        entities:
          - entity: light.luce_bianca
            tap_action:
              action: toggle
          - light.luce_rgb
          - entity: input_boolean.sveglia
            tap_action:
              action: toggle
            icon: mdi:weather-sunny
          - entity: script.luce_notte
            tap_action:
              action: toggle
            icon: mdi:weather-night
          - entity: script.inverti_luci
            tap_action:
              action: toggle
            icon: mdi:yin-yang
          - binary_sensor.porta
          - binary_sensor.interruttore
# Luci natale
      - type: glance
        title: Luci natale
        columns: 4
        show_state: false
        entities:
          - input_datetime.luci_natale_ora_on
          - input_datetime.luci_natale_ora_off
          - light.luci_natale_sala
          - light.luci_natale_terrazzo
          - input_datetime.luci_albero_ora_off
          - light.albero_di_natale
          - light.stella_di_natale
# Fine luci natale
      - type: glance
        title: Settaggi
        columns: 2
        show_state: false
        entities:
          - entity: input_number.minuti_luci_off
            icon: mdi:timer
          - entity: input_datetime.ora_sveglia
            icon: mdi:bell-ring-outline
          - entity: input_number.delay_sorveglia
            icon: mdi:timer
          - entity: script.riavvia_ha
            icon: mdi:restart
      - type: entities
        title: HA Info
        show_header_toggle: false
        entities:
          - sensor.current_version
          - binary_sensor.updater
          - sun.sun
          - sensor.time
          - sensor.date
          - entity: sensor.auto_update_log
            icon: mdi:file
