title: Home assistant

views:
  - title: Main
    id: main
    cards:
      - type: entities
        title: Raspberry
        show_header_toggle: false
        entities:
          - sensor.processor_use
          - sensor.processor_temp
          - sensor.memory_use_percent
          - sensor.disk_use_percent
          - sensor.uptime
      - type: entities
        title: IPC Info
        show_header_toggle: false
        entities:
          - switch.carica_telefono
          - sensor.ip_camera_battery_level
          - sensor.ip_camera_battery_temperature
          - sensor.ip_camera_battery_voltage
      - type: picture-entity
        entity: camera.ip_camera
      - type: glance
        title: Camera
        columns: 3
        show_state: false
        entities:
          - entity: light.luce_bianca
            tap_action:
              action: toggle
          - light.luce_rgb
          - entity: script.luce_sveglia
            tap_action:
              action: toggle
            icon: mdi:weather-sunny
          - entity: script.luce_notte
            tap_action:
              action: toggle
            icon: mdi:weather-night
          - entity: script.inverti_luci
            tap_action:
              action: toggle
            icon: mdi:yin-yang
          - binary_sensor.porta
          - binary_sensor.interruttore
        #   - entity: light.luci_natale_sala
        #     tap_action:
        #       action: toggle
        #   - entity: light.luci_natale_studio
        #     tap_action:
        #       action: toggle
        #   - entity: light.luci_albero
        #     tap_action:
        #       action: toggle
      - type: glance
        title: Settaggi
        columns: 3
        show_state: false
        entities:
          - entity: input_number.minuti_luci_off
            icon: mdi:timer
          - entity: input_datetime.sveglia
            icon: mdi:bell-ring-outline
          - entity: script.riavvia_ha
            icon: mdi:restart
      - type: entities
        title: HA Info
        show_header_toggle: false
        entities:
          - sensor.current_version
          - binary_sensor.updater
          - sun.sun
          - sensor.time
          - sensor.date
          - entity: sensor.auto_update_log
            icon: mdi:file
